### ISSUE TITLE
Could not connect to the endpoint URL: "https://config.ap-northeast-3.amazonaws.com/"

### ISSUE THREAD

**Issue by Parthmonga** [awslabs/aws-security-benchmark#77]
The script is failing with an error, seems like Osaka-local(ap-northeast-3) is not available to all the AWS Accounts.
 
Traceback (most recent call last):
  File "aws_cis_foundation_framework.py", line 2403, in <module>
    lambda_handler("test", "test")
  File "aws_cis_foundation_framework.py", line 2298, in lambda_handler
    control2.append(control_2_5_ensure_config_all_regions(region_list))
  File "aws_cis_foundation_framework.py", line 958, in control_2_5_ensure_config_all_regions
    response = configClient.describe_configuration_recorder_status()
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/monparth/.virtualenvs/myproject/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://config.ap-northeast-3.amazonaws.com/"

**Comment by obijan42** [comment]
Here's the fix I wrote for that:
https://github.com/obijan42/aws-security-benchmark/commit/c73c872217a4f9d5751b3e7d90739ecd521c4030
