### ISSUE TITLE
Throttling Error

### ISSUE THREAD

**Issue by echobb8** [awslabs/aws-security-benchmark#80]
When running this script on an EC2 instance, I keep getting this error:

`# python aws-cis-foundation-benchmark-checklist.py 
Traceback (most recent call last):
  File "aws-cis-foundation-benchmark-checklist.py", line 2403, in <module>
    lambda_handler("test", "test")
  File "aws-cis-foundation-benchmark-checklist.py", line 2260, in lambda_handler
    cred_report = get_cred_report()
  File "aws-cis-foundation-benchmark-checklist.py", line 1935, in get_cred_report
    while IAM_CLIENT.generate_credential_report()['State'] != "COMPLETE":
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Throttling) when calling the GenerateCredentialReport operation (reached max retries: 4): Rate exceeded`

Any idea on how to resolve this?

**Comment by rajikrishnamoorthy** [comment]
@echobb8 was this error resolved?

**Comment by kimho22** [comment]
Hi @echobb8, How did you fix this error
